#%RAML 1.0
title: Notification API
baseUri: http://localhost:4010
mediaType: application/json

/notification:
    /messages/{fileId}:
        post:
            description: Send bulk of emails

    /confirmation:
        post:
            description: Send confirmation email
    /recover:
    	post:
    		description: Send email to recover email.
